Output example/demo.gif

Set Width 1600
Set Height 1050


Type "json-patcher interactive --patch-file example/patch.yaml"
Sleep 0.5s
Enter


Sleep 0.8s
Down
Sleep 0.8s
Up
Sleep 0.8s
Down
Sleep 0.8s
Enter
Sleep 2s

Type "p"
Sleep 3s


Type "t"
Sleep 2s
Type "p"
Sleep 2s
Escape

Sleep 2s
Down 
Type "x"
Sleep 2s

Enter
Sleep 3s
Type "p"
Sleep 3s
Type "a"
Sleep 3s


Type "q"
Sleep 2s
Type "q"

Type "cat generated.json"
Enter
Sleep 3s

